name: Flutter CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Utilise la version de Flutter définie dans pubspec ou la plus récente stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Static Analysis
        run: flutter analyze # Vérifie les erreurs de code et warnings

      - name: Run Unit Tests
        run: flutter test # Exécute vos tests unitaires

      - name: Build APK (Release)
        run: flutter build apk --release --no-pub

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
