# This is a basic workflow to help you get started with Flutter CI/CD using GitHub Actions.
name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Static Analysis # Permet de vérifier le code sans bloquer l'APK
        run: flutter analyze --no-fatal-warnings --no-fatal-infos
        continue-on-error: true

      - name: Run Unit Tests #Permet de vérifier les tests sans bloquer l'APK
        run: flutter test
        continue-on-error: true # Permet de voir les résultats des tests sans bloquer l'APK

      - name: Build APK (Release) #Permet de construire l'APK même si les étapes précédentes ont échoué
        run: flutter build apk --release --no-pub

      - name: Upload APK Artifact #Permet de télécharger l'APK même si les étapes précédentes ont échoué
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload to Firebase App Distribution #Permet de distribuer l'APK même si les étapes précédentes ont échoué
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups dev-team
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIAL_FILE_CONTENT }}  # Clé de service Google Cloud Platform pour l'authentification avec Firebase CLI
